// <auto-generated />
using System;
using Infrastructure.Data.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504043627_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_AuditLogs_ChangedBy");

                    b.HasIndex("EntityName")
                        .HasDatabaseName("IX_AuditLogs_EntityName");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Given")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("MedicineRecord");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0684cf2-f249-41f6-af83-0a75e0a5e7d3"),
                            Given = true,
                            MedicineName = "Atenolol",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f94fc6-c542-4ae9-ade6-3c40cd2262d8"),
                            Given = true,
                            MedicineName = "Sertraline",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4bbd018f-b297-4973-85e9-5be5b0499834"),
                            Given = false,
                            MedicineName = "Bisoprolol",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Timestamp = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f58ba2-c394-4f8c-b058-c13766689c79"),
                            Given = false,
                            MedicineName = "Quetiapine",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Timestamp = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextAllowedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("PainkillerRecord");
                });

            modelBuilder.Entity("Domain.Entities.PhoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PhoneAssignments");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrafficLightStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            FirstName = "",
                            Initials = "A",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            FirstName = "",
                            Initials = "B",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123"),
                            FirstName = "",
                            Initials = "C",
                            LastName = "",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            FirstName = "",
                            Initials = "D",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345"),
                            FirstName = "",
                            Initials = "E",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            FirstName = "",
                            Initials = "F",
                            LastName = "",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567"),
                            FirstName = "",
                            Initials = "GA",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9abc-def012345678"),
                            FirstName = "",
                            Initials = "H",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789"),
                            FirstName = "",
                            Initials = "I",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890"),
                            FirstName = "",
                            Initials = "J",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901"),
                            FirstName = "",
                            Initials = "K",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9abc-def0-123456789012"),
                            FirstName = "",
                            Initials = "GB",
                            LastName = "",
                            TrafficLightStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("IX_ResidentNotes_ResidentId");

                    b.ToTable("ResidentNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-7890-abcdef012345"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident A's note.",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3")
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-8901-bcdef0123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident B's note.",
                            ResidentId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0")
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9012-cdef01234567"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident C's note.",
                            ResidentId = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123")
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-0123-def012345678"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident D's note.",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234")
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-7890-1234-ef0123456789"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident E's note.",
                            ResidentId = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345")
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-8901-2345-f0123456789a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident F's note.",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456")
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9012-3456-0123456789ab"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GA's note.",
                            ResidentId = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567")
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-6789-0123-4567-123456789abc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident H's note.",
                            ResidentId = new Guid("b7c8d9e0-1234-5678-9abc-def012345678")
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-7890-1234-5678-23456789abcd"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident I's note.",
                            ResidentId = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789")
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-8901-2345-6789-3456789abcde"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident J's note.",
                            ResidentId = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890")
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9012-3456-7890-456789abcde0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident K's note.",
                            ResidentId = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901")
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-0123-4567-8901-56789abcde01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-1234-5678-9012-6789abcde012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note 2.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "308f6599-7b53-4c6a-9351-24c4bac486d6",
                            Email = "PederRasmussen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PEDERRASMUSSEN@EXAMPLE.COM",
                            NormalizedUserName = "PEDERRASMUSSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFQtIzyHMJUTbXzdvve7SzNLxfOZtCbJL6KqeETyuhhO1Tykpx93i+EKNBDBaeTfOw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd7c55e7-92e4-427c-9979-e27e9c3edf79",
                            TwoFactorEnabled = false,
                            UserName = "pederrasmussen@example.com"
                        },
                        new
                        {
                            Id = new Guid("4711a300-711e-4132-86d4-cafd3f11deec"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "592e7e87-3b40-4c16-b273-80e761220b74",
                            Email = "SanneJohansen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANNEJOHANSEN@EXAMPLE.COM",
                            NormalizedUserName = "SANNEJOHANSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP4hQYYYdY78rx4NPLIZEDjVgVEEYTh4OsQUiYdtCsk0N0wj8ouCqmSVT7mJ+LucMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "abbfa943-9006-4836-ab90-1237ffc5def3",
                            TwoFactorEnabled = false,
                            UserName = "sannejohansen@example.com"
                        },
                        new
                        {
                            Id = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8afb0c58-a696-41f3-a2c1-9c2fe1bd99ac",
                            Email = "ThorDanrsøn@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "THORDANRSØN@EXAMPLE.COM",
                            NormalizedUserName = "THORDANRSØN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIIzFJqgJNrjumuWjOgLnulSTi+e73nJFSZZYCwdruf1VEaXCe3ibXXeWvOuqaoCvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b46625e8-be83-4946-8627-e0110b81b628",
                            TwoFactorEnabled = false,
                            UserName = "thordanrsøn@example.com"
                        },
                        new
                        {
                            Id = new Guid("37155b80-7111-422a-aba6-89d7070f1644"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b9f22d0-46cc-466b-be87-58326bc0316e",
                            Email = "PerNielsen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PERNIELSEN@EXAMPLE.COM",
                            NormalizedUserName = "PERNIELSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5YN/fzMw7nouwHBkV1JWuqBTFvPLLQCDBDXBD5NZhoxOFYBaodxzi8mcZhFwM+9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae95baa2-00b5-494b-8e70-67248046aae8",
                            TwoFactorEnabled = false,
                            UserName = "pernielsen@example.com"
                        },
                        new
                        {
                            Id = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f086ccb0-6f68-45e4-8f5f-3ef283d5c53f",
                            Email = "AndersJensen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDERSJENSEN@EXAMPLE.COM",
                            NormalizedUserName = "ANDERSJENSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJsaVzRLk4V3/sKXpd5bskZlVg5NEtmhfJa6d8Z6cgTO5T+8AgzIEAyfU5yaf4f1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc087b7e-f95c-4eaf-9c0b-6dd1ff11029b",
                            TwoFactorEnabled = false,
                            UserName = "andersjensen@example.com"
                        },
                        new
                        {
                            Id = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "046f902c-2e92-42c7-996f-01a453c1a391",
                            Email = "KasperHolm@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KASPERHOLM@EXAMPLE.COM",
                            NormalizedUserName = "KASPERHOLM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL+LJvqxDp+BG9x4LtkYAeAZbVL3u63od+w0JKRnVFCwpx1OINAl9QaItnmaX3I4DQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b80ae29-c350-47d7-91d3-52e8850e516f",
                            TwoFactorEnabled = false,
                            UserName = "kasperholm@example.com"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.MedicineStatusView", b =>
                {
                    b.Property<int>("ActiveMedicines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("medicinestatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PainkillerStatusView", b =>
                {
                    b.Property<int>("ActivePainkillers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("painkillerstatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PhoneAssignmentView", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vwPhoneAssignment", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.ResidentNoteView", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("vwResidentNote", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa"),
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d"),
                            Name = "superuser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae"),
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanViewMedicine",
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanManageResidents",
                            RoleId = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanViewMedicine",
                            RoleId = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Painkillers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Notes")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("Notes");

                    b.Navigation("Painkillers");
                });
#pragma warning restore 612, 618
        }
    }
}
