// <auto-generated />
using System;
using Infrastructure.Data.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Given")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("MedicineRecord");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0684cf2-f249-41f6-af83-0a75e0a5e7d3"),
                            Given = true,
                            MedicineName = "Atenolol",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f94fc6-c542-4ae9-ade6-3c40cd2262d8"),
                            Given = true,
                            MedicineName = "Sertraline",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4bbd018f-b297-4973-85e9-5be5b0499834"),
                            Given = false,
                            MedicineName = "Bisoprolol",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Timestamp = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f58ba2-c394-4f8c-b058-c13766689c79"),
                            Given = false,
                            MedicineName = "Quetiapine",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Timestamp = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextAllowedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("PainkillerRecord");
                });

            modelBuilder.Entity("Domain.Entities.PhoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PhoneAssignments");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("TokenHash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrafficLightStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            FirstName = "",
                            Initials = "A",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            FirstName = "",
                            Initials = "B",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123"),
                            FirstName = "",
                            Initials = "C",
                            LastName = "",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            FirstName = "",
                            Initials = "D",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345"),
                            FirstName = "",
                            Initials = "E",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            FirstName = "",
                            Initials = "F",
                            LastName = "",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567"),
                            FirstName = "",
                            Initials = "GA",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9abc-def012345678"),
                            FirstName = "",
                            Initials = "H",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789"),
                            FirstName = "",
                            Initials = "I",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890"),
                            FirstName = "",
                            Initials = "J",
                            LastName = "",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901"),
                            FirstName = "",
                            Initials = "K",
                            LastName = "",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9abc-def0-123456789012"),
                            FirstName = "",
                            Initials = "GB",
                            LastName = "",
                            TrafficLightStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("IX_ResidentNotes_ResidentId");

                    b.ToTable("ResidentNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-7890-abcdef012345"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident A's note.",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3")
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-8901-bcdef0123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident B's note.",
                            ResidentId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0")
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9012-cdef01234567"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident C's note.",
                            ResidentId = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123")
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-0123-def012345678"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident D's note.",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234")
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-7890-1234-ef0123456789"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident E's note.",
                            ResidentId = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345")
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-8901-2345-f0123456789a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident F's note.",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456")
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9012-3456-0123456789ab"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GA's note.",
                            ResidentId = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567")
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-6789-0123-4567-123456789abc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident H's note.",
                            ResidentId = new Guid("b7c8d9e0-1234-5678-9abc-def012345678")
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-7890-1234-5678-23456789abcd"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident I's note.",
                            ResidentId = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789")
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-8901-2345-6789-3456789abcde"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident J's note.",
                            ResidentId = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890")
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9012-3456-7890-456789abcde0"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident K's note.",
                            ResidentId = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901")
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-0123-4567-8901-56789abcde01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-1234-5678-9012-6789abcde012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note 2.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cefa6ccf-2a18-4886-8a0d-3a3c48a78e1e",
                            Email = "PederRasmussen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PEDERRASMUSSEN@EXAMPLE.COM",
                            NormalizedUserName = "PEDERRASMUSSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3OHVxiFL7WdDKJ4uouLTSwxM62Y70n1BF5ls9apFWiAt2ZSDz2kjfE1Ds4Gngo/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35fecfcc-3bb3-4cfa-b389-e29e2ede1e8a",
                            TwoFactorEnabled = false,
                            UserName = "pederrasmussen@example.com"
                        },
                        new
                        {
                            Id = new Guid("4711a300-711e-4132-86d4-cafd3f11deec"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b56c7e7d-908a-400e-bc70-20b8348e054d",
                            Email = "SanneJohansen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANNEJOHANSEN@EXAMPLE.COM",
                            NormalizedUserName = "SANNEJOHANSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENnW9Lqqioz4a7P5h+ftmTr1d7AcmhQWeqCafGfJkvlWhqhB0C2ywJramSuUSG6UxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47043eed-c997-4bdb-be22-e9585e840f6c",
                            TwoFactorEnabled = false,
                            UserName = "sannejohansen@example.com"
                        },
                        new
                        {
                            Id = new Guid("30cffcf9-5784-4fa9-9c10-c013ef3faf16"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8178e80-14a3-4d5e-aac7-2f61ec3f95d0",
                            Email = "ThorDanrsøn@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "THORDANRSØN@EXAMPLE.COM",
                            NormalizedUserName = "THORDANRSØN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAqpMy8xptCulkIfDl/e/BM6r9y9ACP4nl3HNoiHPpI4PTHM37gjFuG5yav3eWjEgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1a893f4-fc1c-4ff7-8f01-dfe7fd50e64c",
                            TwoFactorEnabled = false,
                            UserName = "thordanrsøn@example.com"
                        },
                        new
                        {
                            Id = new Guid("37155b80-7111-422a-aba6-89d7070f1644"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e766dfc-fbf5-4cb5-8d41-4be95035207b",
                            Email = "PerNielsen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PERNIELSEN@EXAMPLE.COM",
                            NormalizedUserName = "PERNIELSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOXqsxmahw0pubRYxwaKiSk9iMl3sRdEVqCnDAjlgTZ0Z2sUguu8ha/7Fr9mUsXXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d23e29a-e6ea-4ae5-8169-9e5e5bcfdfdc",
                            TwoFactorEnabled = false,
                            UserName = "pernielsen@example.com"
                        },
                        new
                        {
                            Id = new Guid("b836e975-e775-48bc-8b84-5d2bdd5bd87a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21b6dc1f-dce9-48af-88ae-32f06dc435e4",
                            Email = "AndersJensen@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDERSJENSEN@EXAMPLE.COM",
                            NormalizedUserName = "ANDERSJENSEN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEKKDiP8OUipbaXmWKmJuEX+pCCHblRGWpA57B4oK8j012tx1xrAvkBgDKCTU9t7mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "007a5b1f-95c7-4377-b0be-8f030591168b",
                            TwoFactorEnabled = false,
                            UserName = "andersjensen@example.com"
                        },
                        new
                        {
                            Id = new Guid("48245a9c-f2a5-4e8f-9554-b6acc9206d37"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86b92d63-4845-4bda-b1f5-2748732cfeb6",
                            Email = "KasperHolm@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KASPERHOLM@EXAMPLE.COM",
                            NormalizedUserName = "KASPERHOLM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHhAcZDyk1KmEwRd+twNXJ6yHCWCDsw38jtX+MTpk/RmdUdt5WZAV46UZNdXvHsV+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "897045a9-a34e-42a1-9bee-97a94bb40c87",
                            TwoFactorEnabled = false,
                            UserName = "kasperholm@example.com"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.MedicineStatusView", b =>
                {
                    b.Property<int>("ActiveMedicines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("medicinestatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PainkillerStatusView", b =>
                {
                    b.Property<int>("ActivePainkillers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("painkillerstatusview", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.PhoneAssignmentView", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vwPhoneAssignment", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Persistent.Views.ResidentNoteView", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("vwResidentNote", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa"),
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d"),
                            Name = "superuser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae"),
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanViewMedicine",
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanManageResidents",
                            RoleId = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanViewMedicine",
                            RoleId = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3a21f8e1-885b-4394-abf0-ed0baeea239b"),
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Painkillers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Notes")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("Notes");

                    b.Navigation("Painkillers");
                });
#pragma warning restore 612, 618
        }
    }
}
